stages:
  - eslint
  - build
  - deploy

Eslint:
  stage: eslint
  image: node:16.5.0
  script:
    - yarn
    - yarn lint
  only:
    - merge_requests

Build:
  stage: build
  image: node:16.5.0
  script:
    - yarn
    - yarn build
  only:
    - merge_requests
  artifacts:
    paths:
      - node_modules/
      # - build/

Deploy:
  stage: deploy
  environment:
    name: production
    url: https://distracted-swartz-dde704.netlify.app/
  only:
    - merge_requests
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
