stages:
  - eslint
  - build
  - deploy

Eslint:
  stage: eslint
  image: node:16.5.0
  script:
    - yarn
    - yarn lint
  only:
    - merge_requests

Build:
  stage: build
  image: node:16.5.0
  script:
    - yarn
    - yarn build
  only:
    - merge_requests
  artifacts:
    paths:
      - node_modules/
      - build/

Deploy:
  stage: deploy
  image: node:16.5.0
  script:
    - yarn global add netlify-cli
    - netlify deploy --dir=build --prod
  only:
    - merge_requests
