stages:
  - eslint
  - build

Eslint:
  stage: eslint
  image: node:16.5.0
  script:
    - yarn
    - yarn lint
  only:
    - merge_requests

Build:
  stage: build
  image: node:16.5.0
  script:
    - yarn
    - yarn build
  only:
    - merge_requests
  artifacts:
    paths:
      - node_modules/
